Repository TickyTocky/TickyTocky, pull requests merged in 2024-01, with the labels that each got.

#20 [24-01-29] eslint "arrow-body-style" rule 수정
  .eslintrc.json
Labels: fix

#16 [24-01-28 고성선] button 컴포넌트 구현
  src/components/common/button/BaseButton.jsx
  src/components/common/button/Button.module.scss
  src/components/common/button/IconButton.jsx
  src/components/common/button/IconButton.module.scss
  src/components/common/button/LinkButton.jsx
  src/components/common/button/MixButton.jsx
Labels: enhancement

#19 [24-01-28 허우림] CommonModal, IconModal 구현
  package-lock.json
  package.json
  public/svg/ic-delete.svg
  src/components/Layout/modal/CommonModal.jsx
  src/components/Layout/modal/IconModal.jsx
  src/components/Layout/modal/Modal.module.scss
  src/constants/importImage.js
  src/pages/_app.js
  src/stores/useModalStore.js
  src/styles/variables/_levels.scss
Labels: enhancement

#8 [24-01-28 허우림] Nav 구현
  public/svg/ic-add-active.svg
  public/svg/ic-logout-hover.svg
  public/svg/ic-logout.svg
  public/svg/ic-nav-active.svg
  public/svg/ic-nav.svg
  src/components/Layout/Nav/Nav.module.scss
  src/components/Layout/Nav/index.jsx
  src/components/nav/LinkButton.jsx
  src/components/nav/ModalButton.jsx
  src/components/nav/NavButton.module.scss
  src/constants/importImage.js
  src/constants/nav.js
  src/constants/navMockData.js
Labels: enhancement

#34 [24-01-31 유미정] Avatar 구현
  public/svg/ic-arrow-down.svg
  public/svg/ic-arrow-up-active.svg
  public/svg/ic-arrow-up.svg
  src/components/common/Avatar/Avatar.module.scss
  src/components/common/Avatar/index.jsx
  src/constants/importImage.js
Labels: enhancement

#36 [24-01-31 유미정] InvitationMembers 구현
  public/svg/ic-add.svg
  src/components/common/InvitationMembers/InvitationMembers.module.scss
  src/components/common/InvitationMembers/index.jsx
  src/constants/importImage.js
  src/hooks/useInvitationMembers.js
Labels: enhancement

#37 [24-01-31 유미정] MyHeader, BoardHeader 구현
  public/svg/ic-home.svg
  public/svg/ic-settings.svg
  src/components/layout/Header/BoardHeader.jsx
  src/components/layout/Header/BoardHeader.module.scss
  src/components/layout/Header/MyHeader.jsx
  src/components/layout/Header/MyHeader.module.scss
  src/components/layout/Header/index.jsx
  src/constants/importImage.js
Labels: enhancement

#39 [24-01-31 유미정] Breadcrumb 구현
  public/svg/ic-arrow-right.svg
  src/components/auth/common/Breadcrumb/Breadcrumb.module.scss
  src/components/auth/common/Breadcrumb/index.jsx
  src/constants/importImage.js
Labels: enhancement

#35 [24-01-31 유미정] ProfileModal 구현
  src/components/common/ProfileModal/ProfileModal.module.scss
  src/components/common/ProfileModal/index.jsx
Labels: enhancement

#44 [24-01-31 유미정] Breadcrumb 폴더 위치 변경
  src/components/common/Breadcrumb/Breadcrumb.module.scss
  src/components/common/Breadcrumb/index.jsx
Labels: bug

#17 [24-01-28 우준석] DropDown 구현
  public/svg/ic-arrow-down-active.svg
  public/svg/ic-arrow-down-default.svg
  src/components/common/DropDown/DropDown.module.scss
  src/components/common/DropDown/ParentsDropDown.jsx
  src/components/common/DropDown/index.jsx
  src/components/common/DropDown/mock-assignees.json
  src/components/common/DropDown/mock-columnlist.json
  src/components/common/DropDown/mock-timeline.json
  src/components/common/DropDownTag/DropDownTag.module.scss
  src/components/common/DropDownTag/index.jsx
  src/constants/importImage.js
  src/hooks/useDropDownDetectClose.jsx
  src/styles/variables/_colors.scss
Labels: enhancement

#25 [24-01-29 우준석] TagField 구현
  public/svg/ic-remove-default.svg
  src/components/common/TagField/ParentTagField.jsx
  src/components/common/TagField/TagField.module.scss
  src/components/common/TagField/index.jsx
  src/constants/importImage.js
Labels: enhancement

#41 [24-01-31 고성선] button 컴포넌트 focus 미적용 및 iconSize 16x16 추가
  src/components/common/button/Button.module.scss
  src/components/common/button/IconButton.jsx
  src/components/common/button/IconButton.module.scss
Labels: bug
